"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from MathLib.numberTheory import fibonacci
from MathLib.constants import golden

BOUND_INCLUSIVE = 4 * 10**6

def main():
    sum = 0
    index = 3

    cur = fibonacci(index) # F_3 = 2
    while cur < BOUND_INCLUSIVE:
        sum += cur
        index += 3
        cur = fibonacci(index)
    
    print(sum)

if __name__ == "__main__":
    main()